### ISSUE TITLE
Add PR review process and general acceptance criteria to contributing guide

### ISSUE THREAD

**Issue by yftacherzog** [redhat-beyond/beyond08-group3#12]
The contributing guide needs to define the process for reviewing a PR and the quality of the commits.

Some suggestions:
- Descriptive commit message titles and bodies, explaining what the PR is about and if it depends on any other unmerged PRs
- Students-driven quality review cycles (no LGTMs) and only then mentors provide their reviews.
- Code review needs to be according to the task requirements - i.e. you need to know the acceptance criteria of the task before reviewing.
- Code needs to be merged before the weekend.

**Comment by pazMenachem** [comment]
"Please note that at least two team members of the group should review and approve the pull request before asking the mentors to review and merge."
we did mention, are we missing something else?

**Comment by pazMenachem** [comment]
on it.

**Comment by yftacherzog** [comment]
> on it.

Cool. have in mind this is not for this demo though.
