### ISSUE TITLE
fix server address

### ISSUE THREAD

**Issue by pazMenachem** [redhat-beyond/beyond08-group3#14]
https://github.com/redhat-beyond/beyond08-group3/blob/890f615b8e124afa814800a1b04b989d2173fd43/setup.sh#L15
the address mentioned above, doesn't open any webpage.
please correct it with the following:
http://127.0.0.1:8000/

**Comment by LiorSilberman** [comment]
Are yo sure? for me it's working.
make sure you enter the follow commands:
vagrant up
vagrant ssh
cd /vagrant
pipenv run python manage.py runserver 0.0.0.0:8000

and then try to open the link:
http://127.0.0.1:8000/

**Comment by pazMenachem** [comment]
thats the thing, when you do vagrant up, the server link should be http://127.0.0.1:8000/.
use vagrant up command and ull see the follows 
![image](https://user-images.githubusercontent.com/83594870/201517452-6c7ca405-0920-48fd-8bed-73ff17ab556b.png)

the server link doesnt work

**Comment by thetaxas2468** [comment]
I think 0.0.0:8000 is okay

by typing 127.0.0.1 is for local host computer in port 8000

**Comment by yftacherzog** [comment]
See the documentation here:
https://docs.djangoproject.com/en/4.1/ref/django-admin/#django-admin-runserver

I think 0.0.0.0 is ok. It means that the server can be accessed from all of the host ip addresses. 127.0.0.1 will mean you can access it only from the loopback interface which is available only locally.

**Comment by pazMenachem** [comment]
got it
