### ISSUE TITLE
Add pytest to our github 

### ISSUE THREAD

**Issue by thetaxas2468** [redhat-beyond/beyond08-group3#29]
#27

**Comment by thetaxas2468** [comment]
Pytest has been added to our github waiting to be merged

**Comment by yftacherzog** [comment]
@thetaxas2468 the link should be the other way around. You should have the issue mentioned on the PR. See this link: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
I linked it manually this time.
