### ISSUE TITLE
Adding some new functions and tests to product module

### ISSUE THREAD

**Issue by thetaxas2468** [redhat-beyond/beyond08-group3#32]
Functions are to get all the products from the data base,and we have tested it using pytest with test called get_all_products.

**Comment by thetaxas2468** [comment]
Functions are to get all the products from the data base,and we have tested it using pytest with test called get_all_products

**Comment by yftacherzog** [comment]
> Functions are to get all the products from the data base,and we have tested it using pytest with test called get_all_products

This should be the content of the first comment - where you currently have the link to the PR.
Your first comment should be the description of the issue.

**Comment by thetaxas2468** [comment]
> > Functions are to get all the products from the data base,and we have tested it using pytest with test called get_all_products
> 
> This should be the content of the first comment - where you currently have the link to the PR. Your first comment should be the description of the issue.

Understood
